const GET_VIDEOGAME = "GET_VIDEOGAME";
const GET_BY_ID = "GET_BY_ID"
const SET_SEARCH = "SET_SEARCH";
const GET_LIST_DISPAY = "GET_LIST_DISPAY";
const SET_LIST_DISPAY = "SET_LIST_DISPAY";
const SET_PAGE ="SET_PAGE";
const SET_FILTERS = "SET_FILTERS";
const GET_GENRES = "GET_GENRES";
const SET_GENRES = "SET_GENRES";
const SET_VIDEOGAMELIST = "SET_VIDEOGAMELIST";
const SET_NEW_VIDEOGAME_GENRE = "SET_NEW_VIDEOGAME_GENRE";
const POST_GENRE = "POST_GENRE";
const POST_VIDEOGAME = "POST_VIDEOGAME";
const SET_SEARCH_ID = "SET_SEARCH_ID";
const UPDATE_VIDEOGAME_DESCRIPTION = "UPDATE_VIDEOGAME_DESCRIPTION";


module.exports = {
  GET_VIDEOGAME,
  GET_BY_ID,
  SET_VIDEOGAMELIST,
  GET_LIST_DISPAY,
  GET_GENRES,
  SET_SEARCH,
  SET_LIST_DISPAY,
  SET_PAGE,
  SET_FILTERS,
  SET_GENRES,
  SET_NEW_VIDEOGAME_GENRE,
  POST_GENRE,
  POST_VIDEOGAME,
  SET_SEARCH_ID,
  UPDATE_VIDEOGAME_DESCRIPTION
};
